[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "GuWa56HaXfkYEH2eDHSsrAsCh5MzznvF99LrLoP4HHEe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/my-solana-wallet/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
